// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the identity of the currently signed-in user.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const info = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail(),
      client_id: ctx.getClientId()
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-projects.ts
import { createClient } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_projects_default = defineTool2({
  name: "list_projects",
  title: "List projects",
  description: "List projects visible to the signed-in user, most recent first.",
  inputSchema: {
    status: z.enum(["planned", "in_progress", "completed", "on_hold", "cancelled"]).optional().describe("Filter by project status."),
    limit: z.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("projects").select("id,name,client_name,status,start_date,end_date,priority").order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-employees.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_employees_default = defineTool3({
  name: "list_employees",
  title: "List employees",
  description: "List employees visible to the signed-in user.",
  inputSchema: {
    search: z2.string().trim().min(1).optional().describe("Match name or employee code."),
    limit: z2.number().int().min(1).max(100).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    let q = supabase.from("employees").select("id,name,employee_code,role,is_active,branch_id").order("name", { ascending: true }).limit(limit);
    if (search) q = q.or(`name.ilike.%${search}%,employee_code.ilike.%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { employees: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/attendance-summary.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var attendance_summary_default = defineTool4({
  name: "attendance_summary",
  title: "Attendance summary",
  description: "Get attendance logs for a date range (defaults to today). Returns rows the signed-in user is permitted to see.",
  inputSchema: {
    date_from: z3.string().describe("Start date, YYYY-MM-DD.").optional(),
    date_to: z3.string().describe("End date, YYYY-MM-DD.").optional(),
    employee_id: z3.string().uuid().optional().describe("Filter to one employee."),
    limit: z3.number().int().min(1).max(200).default(100)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date_from, date_to, employee_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const today = new Date(Date.now() + 4 * 60 * 60 * 1e3).toISOString().slice(0, 10);
    const from = date_from ?? today;
    const to = date_to ?? from;
    const supabase = supabaseForUser3(ctx);
    let q = supabase.from("attendance_logs").select(
      "id,employee_id,date,office_punch_in,office_punch_out,total_work_minutes,total_travel_minutes,status"
    ).gte("date", from).lte("date", to).order("date", { ascending: false }).limit(limit);
    if (employee_id) q = q.eq("employee_id", employee_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { from, to, logs: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "dpnjkqwzsjydntwqxsbw";
var mcp_default = defineMcp({
  name: "bebright-planner-mcp",
  title: "BeBright Planner",
  version: "0.1.0",
  instructions: "Tools for BeBright Planner \u2014 a workforce and project management app. Use `whoami` to verify connectivity, `list_projects` and `list_employees` to browse workspace data, and `attendance_summary` to review daily attendance. All tools run as the signed-in user with row-level security applied.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_projects_default, list_employees_default, attendance_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
